### ISSUE TITLE
Cannot import 'misc'

### ISSUE THREAD

**Issue by jkloe** [lquirosd/P2PaLA#15]
When running P2PaLA.py from the current master branch state I get the following error:
```
  File "P2PaLA.py", line 26, in <module>
    from utils import misc
ImportError: cannot import name 'misc'
```

The utils subdirectory does not contain a file 'misc.py'

**Comment by lquirosd** [comment]
There was a missing file on previous commit. I just add the misc.py file to master branch.
Thanks for pointing it out.

**Comment by jkloe** [comment]
thx!
