### ISSUE TITLE
ICDAR 2019 Competition on Baseline Detection (cBAD)?

### ISSUE THREAD

**Issue by mrocr** [lquirosd/P2PaLA#16]
@lquirosd Will you participate in the ICDAR 2019 cBAD competition?
Do you have any plans to optimize P2PaLA?

**Comment by lquirosd** [comment]
> @lquirosd Will you participate in the ICDAR 2019 cBAD competition?

There are many interesting competitions in the ICDAR'19, we are analyzing that option.

> Do you have any plans to optimize P2PaLA?

Yes, we are actively optimizing the tool in several ways.
