### ISSUE TITLE
Is it possible for fine tune the existing model for different regions?

### ISSUE THREAD

**Issue by lordzuko** [lquirosd/P2PaLA#18]
Hi,

I want to extend this work to find the regions on different documents with different regions (other than defined in the regions list `regions = ["$tip", "$par", "$not", "$nop", "$pag"]`. Is this possible? If so, what change will be needed ? I am new to segmentation problems, please guide.

@lquirosd

**Comment by lquirosd** [comment]
Hi,
That region list is just the default value, you can change it always using ``--regions`` argument, please see the [help](https://github.com/lquirosd/P2PaLA/blob/master/docs/help.md) for details.

**Comment by lordzuko** [comment]
@lquirosd Will this change suffice for fine tuning the model ?

**Comment by lquirosd** [comment]
That change will allow you to train a new model from scratch, fine tuning from a model with different set of regions is not implemented yet.

**Comment by lordzuko** [comment]
@lquirosd Since, the model for region is not open sourced yet, my approach is to train that model using the dataset from the competition and then tune the model on a different dataset with different regions, is this possible? If so, can you please suggest me the changes that are required to be made ?

**Comment by lquirosd** [comment]
Yes, please see this [discussion](https://discuss.pytorch.org/t/correct-way-to-freeze-layers/26714) about the best way to do it on pytorch, and [this](https://blog.revolutionanalytics.com/2016/08/deep-learning-part-2.html) other for a theoretical bit of how to do it.

In the case of P2PaLA, you have to update:
1) options.py: to add a new argument to tell the system to perform fine-tuning.
2) P2PaLa.py: to create the new model, load the previous model correctly and freeze the parameters.

**Comment by lordzuko** [comment]
@lquirosd Thanks for your time, I will read the provided resources and try to implement the suggested changes. I will ask questions, if I will run into some issue. Thanks again !
