### ISSUE TITLE
CPU Mode

### ISSUE THREAD

**Issue by MrOCR** [lquirosd/P2PaLA#2]
@lquirosd Thank you for your hard work.
How can I use P2PaLA on CPU Mode? I don't have any graphics card.

**Comment by lquirosd** [comment]
Hi @MrOCR  
CPU mode is not implemente yet. We are planning to include that feature in a future release.

**Comment by lquirosd** [comment]
Hi @MrOCR 
CPU mode is already available on latest version. Although CPU training is implemented, it's not recommended due the high computational cost, instead please check pre-trained models [here](https://github.com/lquirosd/P2PaLA/blob/master/egs/pre_trained).

**Comment by MrOCR** [comment]
@lquirosd Thanks man
