### ISSUE TITLE
Different predictions when changing the images order in prod_img_list

### ISSUE THREAD

**Issue by danielsernabuitrago** [lquirosd/P2PaLA#25]
I've trained a custom model and I'm using it to predict regions from some images, but I have a problem when I use a file in opts.prod_img_list = images.txt which contains the list of the images to be predicted, but when I change the order of the list, the predictions show different results, even when I'm using the same images.

**Comment by lquirosd** [comment]
Hi, 
Thanks for highlight the issue, we fix it on last commit.

**Comment by danielsernabuitrago** [comment]
Hi Lorenzo,

thanks for your amazing work and for your response to the issue I have
submitted, I have tried the changes you did on the commit you mentioned,
but I have noticed the issue persists, or maybe I have to change one of the
arguments in opts while I am predicting or doing production from a prod
folder?

Thanks a lot in advance for your help.

Daniel Serna B
