### ISSUE TITLE
JoseRPrietoF version?

### ISSUE THREAD

**Issue by deepseek** [lquirosd/P2PaLA#27]
@JoseRPrietoF 
What is different in your version of P2PaLA?

> Modified version to do table segmentation and act separation on Passau and Chancery corpus.
- what do you mean by `act separation`?
- also, when you say `table segmentation`, do you mean it detects baseline, and then extracts text?

**Comment by deepseek** [comment]
@JoseRPrietoF hmmmm.... you removed your p2pala repo
what was your version modified to do best?

**Comment by JoseRPrietoF** [comment]
My version was just for try some experiments on my free time to test some corpus.
At this moment im not working with P2PaLA.
