### ISSUE TITLE
XML generator

### ISSUE THREAD

**Issue by EvertonTomalok** [lquirosd/P2PaLA#29]
Hello.

How can I generate new png XML? Do you use any tool to handle it?

**Comment by lquirosd** [comment]
Hi, 
Do you mean PAGE-XML?

**Comment by EvertonTomalok** [comment]
Exactly!

Because it'll be the input data, or do I talking nonsense things? Haha

I'm used labeling using this tool: https://github.com/tzutalin/labelImg

But I don't know if it's compatible with P2Pala.

Furthermore, congrats for your code... I was developing something very similar, but I think P2PaLa will help a lot.

**Comment by EvertonTomalok** [comment]
Never mind brother... I read again the doc, and I found it: 

`We recommend Transkribus or nw-page-editor to visualize and edit PAGE-xml files.`

**Comment by EvertonTomalok** [comment]
Is it possible to label the png, instead of line as a paragraph?

**Comment by lquirosd** [comment]
Hi,
A line (aka TetxLine, Baseline) is a general element that describes where the text is placed. On the other hand we have a different hierarchic level called a "region" (aka TextRegion), this object is designed to describe some properties of the data, for example: a paragraph is a TextRegion that encompasses one or more TextLines all of them with the type "paragraph". 
So you can label your TextRegion using whatever "type" (paragraph, marginalia, header ...) do you what (using the `custom->structure` field on the PAGE-XML), and assign each TextLine to the corresponding TextRegion.
For more details about PAGE-XML format please check this [paper](https://www.primaresearch.org/www/assets/papers/ICPR2010_Pletschacher_PAGE.pdf)
