### ISSUE TITLE
Implement ARU-Net instead of PRHLT [Suggestion]

### ISSUE THREAD

**Issue by MrOCR** [lquirosd/P2PaLA#3]
@lquirosd 
As-far-as I know, ARU-Net is the most accurate & simpler to use for text/ baselines detection.

https://github.com/TobiasGruening/ARU-Net
https://arxiv.org/abs/1802.03345

**Comment by lquirosd** [comment]
Thanks  for the suggestion. My understanding is ARU-Net main goal is to detect the lines/baselines on the documents. Our main goal is slightly different, we want to extract not only the lines/baselines but the structure of the document in a integrated way and this repository is a window to the work we are doing in that direction.
