### ISSUE TITLE
How to see output polygon drawn on an input image?

### ISSUE THREAD

**Issue by longwall** [lquirosd/P2PaLA#38]
Please advise on utility to draw the output baseline polygon on source image. I see an example on your online page(btw it doesn't work this time, skips the Process button).
But I can't fond a way to look at it on my machine.
If any built-in function please write the cli command:   cmd   data/source_img.jpg  work/results_prod/page/source_img.xml    
-> to  produce drawn countor on source image.
In my run there are   zero-size jpg files  in work/results/prod   
Probably it's a sort of error so it's interesting to draw xml lines over image(s).

**Comment by longwall** [comment]
Please hint how to fix the issue during run 
`python P2PaLA.py --config config_ALAR_min_model_17_12_18_inference.txt  --prev_model egs/pre_trained/ALAR_min_model_17_12_18.pth  --prod_data data/prod --gpu -1
`
I got a set of xml files in work/results/prod/page  and   zero size image files in work/results/prod.
All image files are empty.  Maybe I forgot some start option?

**Comment by lquirosd** [comment]
Hi,
> Please advise on utility to draw the output baseline polygon on source image. I see an example on your online page(btw it doesn't work this time, skips the Process button).
> But I can't fond a way to look at it on my machine.
> If any built-in function please write the cli command: cmd data/source_img.jpg work/results_prod/page/source_img.xml
> -> to produce drawn countor on source image.

Please see point 4 at [USAGE section on README ](https://github.com/lquirosd/P2PaLA#usage). We recommend Transkribus and  nw-page-editor for visualization.

> In my run there are zero-size jpg files in work/results/prod
> Probably it's a sort of error so it's interesting to draw xml lines over image(s).

The "images" you see in ``work/results/prod`` are symbolic links to the original ones provided to the tool. We did not copy the images because it would be a waste of memory.

**Comment by lquirosd** [comment]
> Please hint how to fix the issue during run
> `python P2PaLA.py --config config_ALAR_min_model_17_12_18_inference.txt --prev_model egs/pre_trained/ALAR_min_model_17_12_18.pth --prod_data data/prod --gpu -1 `
> I got a set of xml files in work/results/prod/page and zero size image files in work/results/prod.
> All image files are empty. Maybe I forgot some start option?

As mentioned in the previous comment, those "images" are symbolic links.

**Comment by longwall** [comment]
Thanks a lot!
