### ISSUE TITLE
require opencv-python-headless variant

### ISSUE THREAD

**Issue by bertsky** [lquirosd/P2PaLA#44]
The `requirements.txt` currently lists `opencv-python`, which drags in libraries for windowing systems like X11 – not ideal for headless servers. The Python bindings for OpenCV do offer other build variants like `-contrib` and `-headless` though (which are on PyPI for many platforms, and can also be built by `ENABLE_HEADLESS=1 python setup.py bdist_wheel`).

Therefore I suggest switching to `opencv-python-headless` instead.

**Comment by bertsky** [comment]
In the same spirit, I believe `tensorboardx` and `matplotlib` should be hidden under a feature – becoming opt-in dependencies. (The mechanism is setuptools' `extras_require`, e.g.:
```python
 extras_require={
    'debug': ['tensorboardx', 'matplotlib']
}
```
(or whatever you want to name the visualisation feature).

**Comment by lquirosd** [comment]
Thanks for the comment, but no further development is expected on this repository. I will archive it soon.
