### ISSUE TITLE
General

### ISSUE THREAD

**Issue by MrOCR** [lquirosd/P2PaLA#6]
Discussing general topic.

**Comment by MrOCR** [comment]
Topic: suggestion
@lquirosd You need to merge the `pre_trained/README.md` with the `master/README.md` so it's easier to find for new members.

**Comment by MrOCR** [comment]
Topic: question
@lquirosd
- Can P2PaLA be trained to detect Text-Lines?
- Was `ALAR_min_model_17_12_18.pth` trained to detect baselines or textlines?

**Comment by lquirosd** [comment]
> Topic: suggestion
> 
> @lquirosd You need to merge the `pre_trained/README.md` with the `master/README.md` so it's easier to find for new members.

there is a link on `master/README.md` to `pre_trained/README.md`, there is a lot of work to be done related to pre-trained models, both README files should be updated soon.

**Comment by lquirosd** [comment]
> Topic: question
> 
> * Was `ALAR_min_model_17_12_18.pth` trained to detect base-lines or text-lines?

That model is trained to extract baselines only, but text-lines can be obtained easily from there

> * How to choose the right configurations to train to detect Text-Lines?
>   I have seen the [config help](https://github.com/lquirosd/P2PaLA/blob/master/docs/help.md), but what do you recommend?

This software is not intended to extract text-lines directly, instead we rely on baselines (so users can easily fix any error) and then another software can be used to extract the text-lines from the baselines.

I recommend this software for that task [pageContourGenerator](https://github.com/PRHLT/pageContourGenerator) to generate contours around the baselines (bases on the inter-line distance) and [pageLineExtractor](https://github.com/PRHLT/pageLineExtractor) to extract those contours from the original image (i.e. generate a set of sub-images from the original one).

**Comment by MrOCR** [comment]
Thanks man for sharing the code!
